### ISSUE TITLE
Programming Progress

### ISSUE THREAD

**Issue by kkirsche** [devtees/shirt-ideas#36]
I think it would be really cool to have a shirt based on this quote:

"Measuring programming progress by lines of code is like measuring aircraft building progress by weight."

I think it has potential to be very visual. What are your thoughts?

**Comment by jglovier** [comment]
@kkirsche thanks for the suggestion! I think it's an interesting idea, but having trouble coming up with a compelling way to represent it as an illustration.

**Comment by jglovier** [comment]
Closing this out. The quote is very clever, but it's a bit too complex for a good illustration. I really just can't think of a good way to visualize that quote. The [Programmer tee](http://devtees.com/collections/frontpage/products/programmer-black) quote works well because it's a definition with a linear equation, basically. However this quote is more of an analogy, which just doesn't lend itself to illustration well.

Thanks for the suggestion though! :sparkles:

**Comment by jglovier** [comment]
I actually thought of something that could work for this design and be really interesting. Adding the revist label to remind me to revisit this concept later.

**Comment by jglovier** [comment]
Rough concept sketch:

![image](https://cloud.githubusercontent.com/assets/1319791/10869646/5dfd7166-8083-11e5-9959-f82a38ca3e31.png)

...and inspiration for style/layout...

![image](https://cloud.githubusercontent.com/assets/1319791/10869652/7acb8148-8083-11e5-8ab6-3a0374787ed1.png)

**Comment by kkirsche** [comment]
I like that idea and love the inspirations. I the the typography here could really give it some nice personality with the main theme
