### ISSUE TITLE
Markdown Monday Shopify Error

### ISSUE THREAD

**Issue by bnb** [devtees/shirt-ideas#41]
Hey there.

I went to buy the Red Markdown Monday Set Code Free shirt, and when I click Add to Cart, I get an error page with the following Shopify error:

```
Parameter Missing or Invalid: Required parameter missing or invalid: id 
```

Sucks that I'm going to miss this shirt, as I really wanted one.

**Comment by jglovier** [comment]
Did you select the size? I think that happens when you don't select a size, or you select a size that is unavailable.

**Comment by jglovier** [comment]
It's def a crappy experience though, and I need to fix that.  It used to default to the first size, which was small, and people would forget to change it so they automatically ordered small by mistake.  So it works this way now so that people don't order a small by mistake, but it still is a crappy experience when you get that error.

**Comment by bnb** [comment]
Yes, I selected large on both versions as well as small on the black version, always got the error.

**Comment by jglovier** [comment]
>I selected large on both versions as well as small on the black version, always got the error.

@bnb yeah, that would def explain it. Those sizes were out of stock. We already had limited stock when I launched the promo yesterday. Sorry about that.

**Comment by jglovier** [comment]
@bnb I've really appreciated the work you've put into suggesting shirt designs and participating in this repo, BTW. Feel free to shoot me an email and I'd like to send you a coupon code you can use for any of the shirts we do have in stock.
